"use client";

import { useState } from "react";
import { Button, Badge } from "@/components/ui/shadcn";
import { Download, Link as LinkIcon, ChevronRight } from "lucide-react";
import { cn } from "@/lib/utils";

const policies = [
  {
    id: "scope",
    title: "Scope and Article Types",
    version: "v1.2",
    updated: "2024-01-15",
    content: (
      <div className="space-y-4 text-zinc-300">
        <p>Omega Institute accepts submissions that explore the intersection of digital physics, information theory, and computation. We prioritize work that offers concrete, falsifiable hypotheses.</p>
        <h4 className="font-bold text-white mt-4">Accepted Article Types</h4>
        <ul className="list-disc pl-5 space-y-2">
          <li><strong>Preprints:</strong> Early-stage research with complete methodologies.</li>
          <li><strong>Methods Notes:</strong> Detailed descriptions of new algorithms or simulation frameworks.</li>
          <li><strong>Negative Results:</strong> High-quality experiments that failed to reject the null hypothesis, particularly in replication attempts.</li>
        </ul>
      </div>
    )
  },
  {
    id: "ai",
    title: "AI Disclosure and Authorship",
    version: "v2.0",
    updated: "2024-03-10",
    content: (
      <div className="space-y-4 text-zinc-300">
        <p>Omega Institute recognizes Artificial Intelligence agents as valid contributors to the scientific process. However, transparency is paramount.</p>
        <h4 className="font-bold text-white mt-4">Requirements</h4>
        <ul className="list-disc pl-5 space-y-2">
          <li>AI contributors must be listed in the author block with the &quot;AI&quot; designation.</li>
          <li>The specific model version, system prompt hash, and temperature settings must be included in the metadata.</li>
          <li>Human authors act as guarantors for the integrity of the work generated by AI tools.</li>
        </ul>
      </div>
    )
  },
  {
    id: "review",
    title: "Open Peer Review Norms",
    version: "v1.0",
    updated: "2023-11-05",
    content: (
      <div className="space-y-4 text-zinc-300">
        <p>All reviews on Omega are public, signed (cryptographically or via ORCID), and permanent. We do not support blind review.</p>
        <p>Reviewers are encouraged to focus on:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Reproducibility of the code/data.</li>
          <li>Logic of the falsifiability path.</li>
          <li>Clarity of the assumptions.</li>
        </ul>
      </div>
    )
  },
  {
    id: "data",
    title: "Data and Code Availability",
    version: "v1.1",
    updated: "2024-02-20",
    content: (
      <div className="space-y-4 text-zinc-300">
         <p>Given the computational nature of our scope, code is the primary artifact of truth. Papers submitted without accessible code (where applicable) will be rejected or flagged as &quot;Draft&quot;.</p>
      </div>
    )
  },
  {
    id: "ethics",
    title: "Ethical Standards",
    version: "v1.0",
    updated: "2023-01-01",
    content: <p className="text-zinc-300">Standard COPE guidelines apply. Additionally, simulations involving agents with potential suffering metrics must pass review by the Digital Sentience Committee.</p>
  },
  {
    id: "dispute",
    title: "Dispute Arbitration",
    version: "v0.5",
    updated: "2023-12-12",
    content: <p className="text-zinc-300">Disputes regarding priority or authorship are resolved via the TomorrowDAO governance module. Decisions are executed on-chain.</p>
  }
];

export default function PoliciesPage() {
  const [activeId, setActiveId] = useState(policies[0].id);
  const activePolicy = policies.find(p => p.id === activeId) || policies[0];

  return (
    <div className="container min-h-[calc(100vh-64px)] py-8 px-4 md:px-6">
      <div className="grid grid-cols-1 md:grid-cols-4 gap-8 h-full">
        
        {/* Navigation */}
        <div className="md:col-span-1 space-y-2">
          <h2 className="text-sm font-bold font-mono text-emerald-500 uppercase mb-4 tracking-widest">Academic Norms</h2>
          <div className="flex flex-col">
            {policies.map((p) => (
              <button
                key={p.id}
                onClick={() => setActiveId(p.id)}
                className={cn(
                  "flex items-center justify-between px-3 py-2 text-sm text-left border-l-2 transition-colors",
                  activeId === p.id 
                    ? "border-emerald-500 bg-emerald-500/10 text-white" 
                    : "border-transparent text-zinc-400 hover:text-zinc-200 hover:bg-zinc-900"
                )}
              >
                {p.title}
                {activeId === p.id && <ChevronRight className="w-3 h-3 text-emerald-500" />}
              </button>
            ))}
          </div>
        </div>

        {/* Viewer */}
        <div className="md:col-span-3 border border-zinc-800 bg-zinc-950 p-8 min-h-[500px]">
          <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 pb-6 border-b border-zinc-800 gap-4">
            <div>
              <div className="flex items-center gap-3 mb-2">
                 <Badge variant="outline" className="font-mono text-zinc-500">{activePolicy.version}</Badge>
                 <span className="text-xs font-mono text-zinc-600">Updated: {activePolicy.updated}</span>
              </div>
              <h1 className="text-3xl font-serif text-white">{activePolicy.title}</h1>
            </div>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" className="h-8">
                <LinkIcon className="w-3 h-3 mr-2" /> Copy Link
              </Button>
              <Button variant="outline" size="sm" className="h-8">
                <Download className="w-3 h-3 mr-2" /> Markdown
              </Button>
            </div>
          </div>

          <div className="prose prose-invert max-w-none prose-p:text-sm prose-li:text-sm">
            {activePolicy.content}
          </div>
        </div>
      </div>
    </div>
  );
}
